export { ErrorsPage } from './errors-page';
export { MainPage } from './main-page';
export { PasswordRecoveryPage } from './password-recovery';
export { RegistrationPage } from './registration-page';
export { FeedbackPage } from './feedback-page';
export { CalendarPage } from './calendar-page';
export { ProfilePage } from './profile-page';
export { SettingsPage } from './settings-page';
export { NotFoundPage } from './not-found-page';
