export enum Paths {
    HOME = '/',
    MAIN = '/main',
    AUTH = '/auth',
    REGISTRATION = 'registration',
    CONFIRM_EMAIL = 'confirm-email',
    CHANGE_PASSWORD = 'change-password',
    RESULT = '/result',
    SUCCESS = 'success',
    ERROR = 'error',
    ERROR_LOGIN = 'error-login',
    USER_EXIST = 'error-user-exist',
    ERROR_CHECK_EMAIL_NO_EXIST = 'error-check-email-no-exist',
    ERROR_CHECK_EMAIL = 'error-check-email',
    ERROR_CHANGE_PASSWORD = 'error-change-password',
    SUCESS_CHANGE_PASSWORD = 'success-change-password',
}
